### ISSUE TITLE
Imported Signal Generator nodes do not generate values

### ISSUE THREAD

**Issue by lachlancresswell** [simpleiot/simpleiot#759]
Save the below configuration as `export.yml`, run `siot import --parentID=root < ./export.yml`, login to the web ui and see that the signal generator node does not generate a 'value' point.

Tested on SimpleIOT v0.18.3

```
nodes:
- id: ae4f9bab-3b3b-4271-a806-2c7888266816
  type: device
  parent: root
  points:
  - type: metricNatsCycleNode
    value: 0.13541666666666666
  - type: metricNatsCycleNodeEdgePoint
    value: 1.0
  - type: metricNatsCycleNodePoint
    value: 1.0932835820895523
  - type: metricNatsPendingNodeEdgePoint
  - type: metricNatsPendingNodePoint
  - type: versionApp
    text: v0.18.3
  - type: versionOS
    text: 2024.12.0
  children:
  - id: d1522363-7a52-43c2-8846-eb1a7434a634
    type: user
    parent: ae4f9bab-3b3b-4271-a806-2c7888266816
    points:
    - type: email
      text: admin
    - type: firstName
      text: admin
    - type: lastName
      text: user
    - type: pass
      text: admin
    - type: phone
  - id: 201033c4-ea41-43b7-8afe-585e136be06e
    type: signalGenerator
    parent: ae4f9bab-3b3b-4271-a806-2c7888266816
    points:
    - type: batchPeriod
      value: 250.0
    - type: description
      text: Generator
    - type: initialValue
      value: 10.0
    - type: maxIncrement
      value: 10
    - type: maxValue
      value: 100.0
    - type: minIncrement
      value: -10
    - type: minValue
      value: 0.0
    - type: roundTo
      value: 0.1
    - type: sampleRate
      value: 1.0
    - type: signalType
      text: random walk
```

**Comment by cbrake** [comment]
There have been quite a few changes in SIOT recently:

- the export/import format has been simplified
- store has switched to jetstream, which supports catch-up sync when there is not a connection.

I just tested the following import:

```
apiVersion: 1
nodes:
  - variable:
      description: Var1
      variableType: onOff
  - signalGenerator:
      batchPeriod: 1000
      description: Sine wave
      frequency: 0.1
      initialValue: "0"
      maxValue: 10
      minValue: "0"
      sampleRate: 10
      signalType: sine
      units: V
      value: 0.24471741852425954
      volt: 9.75528258147574
  - sync:
      description: Sync to upstream
      syncCount: 1
      uri: nats://localhost:4333
  - user:
      email: admin
      firstName: admin
      lastName: user
      pass: admin
      phone: ""
```

And it seems to be generating data:

<img width="1234" height="397" alt="Image" src="https://github.com/user-attachments/assets/60f7e522-b058-4f80-8ef9-2b55bc848077" />

Please reopen if you still have issues with latest code.
